export default () => ({
  app: {},
  elements: [],
  compounds: [],
  isotopes: [],
  probableElements: [],
  temperature: 0,
  selectedTemperatureType: 'c',
  isTemperatureTriggered: false,
  isIsotopeFetched: false,
  isCompoundFetched: false,
  showInfoModal: false,
  selectedContentId: null,
  searchText: null,
  isMobile: false,
  isOriented: false,
  selectedPhaseOfMatter: null,
})
